roboptim::StableTimePoint Class Reference
roboptim::StableTimePoint Class Reference
#include <roboptim/trajectory/stable-time-point.hh>
Public Types
typedef Function::value_type value_type
Public Member Functions
StableTimePoint (value_type alpha)
const value_type & getAlpha () const
value_type getTime (Function::interval_t timeRange) const
Member Typedef Documentation
typedef Function::value_type roboptim::StableTimePoint::value_type
Constructor & Destructor Documentation
roboptim::StableTimePoint::StableTimePoint (value_type alpha) [inline, explicit]
Member Function Documentation
const value_type& roboptim::StableTimePoint::getAlpha () const [inline]
Referenced by roboptim::detail::getLimitSpeedName().
value_type roboptim::StableTimePoint::getTime (Function::interval_t timeRange) const [inline]
Referenced by roboptim::Trajectory< DerivabilityOrder >::impl_compute(), roboptim::VectorInterpolation::impl_derivative(), roboptim::visualization::gnuplot::plot_speeds(), roboptim::visualization::gnuplot::plot_xytheta(), and roboptim::VectorInterpolation::variationDerivWrtParam().