roboptim Namespace Reference
roboptim Namespace Reference
Meta-functions, functions and solvers related classes.
Namespaces
namespace detail
namespace visualization
Graphic visualization.
Classes
class AnthropomorphicCostFunction
Cost function from ``An optimal control model unifying holonomic and nonholonomic walking'' Katja Mombaur, Jean-Paul Laumond, Eiichi Yoshida (2008 8th IEEE-RAS Interational Conference on Humanoid Robots).
class CubicBSpline
Cubic B-Spline trajectory.
class FreeTimeTrajectory
Decorate a trajectory to make time scalable.
class Freeze
Add constraints that freeze parameters.
class FrontalSpeed
class LimitOmega
class LimitSpeed
class OrthogonalSpeed
class Polynomial3
Polynomial of degree at most 3.
struct Monomial
Monomial
.
class SplineLength
Approximate the length of a Spline.
class StablePointStateFunction
Trajectory cost function defined by state evaluation at parameter.
class TMax
class StableTimePoint
class StateFunction
Trajectory cost function defined by state evaluation at parameter.
class TrajectoryCost
Meta-function for trajectory cost.
class TrajectorySumCost
Trajectory cost function defined by sum of state evaluations at parameters.
class Trajectory
Abstract trajectory.
class VectorInterpolation
Takes a vector or argument and differentiate it.
Functions
Function::vector_t addScaleToParameters (const Function::vector_t &p, Function::value_type t=1.)
Function::vector_t removeScaleFromParameters (const Function::vector_t &v)
template<typename P >
Freeze< P > makeFreeze (P &problem) throw ()
Polynomial3 operator* (const double &lambda, const Polynomial3 &poly)
Scalar multiplication of a 3rd degree polynomial.
std::ostream & operator<< (std::ostream &o, const Polynomial3 &p)
StableTimePoint operator* (Function::value_type alpha, TMax)
StableTimePoint operator* (TMax, Function::value_type alpha)
boost::shared_ptr
< VectorInterpolation > vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt=1.)
Variables
static const TMax tMax = TMax ()
Detailed Description
Meta-functions, functions and solvers related classes.
Function Documentation
Function::vector_t roboptim::addScaleToParameters (const Function::vector_t & p, Function::value_type t = 1.) [inline]
template<typename P > Freeze<P> roboptim::makeFreeze (P & problem) throw ()
StableTimePoint roboptim::operator* (Function::value_type alpha, TMax) [inline]
StableTimePoint roboptim::operator* (TMax , Function::value_type alpha) [inline]
Polynomial3 roboptim::operator* (const double & lambda, const Polynomial3 & poly)
Scalar multiplication of a 3rd degree polynomial.
References roboptim::Polynomial3::coefs_, and roboptim::Polynomial3::t0_.
std::ostream & roboptim::operator<< (std::ostream & o, const Polynomial3 & p)
References roboptim::Polynomial3::print().
Function::vector_t roboptim::removeScaleFromParameters (const Function::vector_t & v) [inline]
Referenced by roboptim::FreeTimeTrajectory< T >::setParameters().
boost::shared_ptr<VectorInterpolation> roboptim::vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt = 1.) [inline]
Variable Documentation
const TMax roboptim::tMax = TMax () [static]
Referenced by roboptim::LimitOmega< T >::addToProblem(), roboptim::LimitSpeed< T >::addToProblem(), roboptim::StablePointStateFunction< T >::addToProblem(), roboptim::StateFunction< T >::addToProblem(), roboptim::visualization::gnuplot::detail::PlotLimitSpeed< T >::operator()(), roboptim::visualization::gnuplot::plot_speeds(), roboptim::visualization::gnuplot::plot_xy(), roboptim::visualization::gnuplot::plot_xytheta(), roboptim::FreeTimeTrajectory< T >::resize(), and roboptim::FreeTimeTrajectory< T >::unscaleTime().