roboptim::VectorInterpolation Class Reference
roboptim::VectorInterpolation Class Reference
Takes a vector or argument and differentiate it.
#include <roboptim/trajectory/vector-interpolation.hh>
Public Types
typedef boost::shared_ptr
< VectorInterpolation > VectorInterpolationShPtr_t
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS (Trajectory< 3 >)
ROBOPTIM_IMPLEMENT_CLONE (VectorInterpolation)
VectorInterpolation (const vector_t &x, size_type outputSize, value_type dt) throw (std::runtime_error)
~VectorInterpolation () throw ()
void setParameters (const vector_t &) throw (std::runtime_error)
Store parameters and update coefficients.
jacobian_t variationConfigWrtParam (double t) const throw ()
Get the variation of a configuration with respect to parameter vector.
jacobian_t variationDerivWrtParam (double t, size_type order) const throw ()
Get the variation of a derivative with respect to parameter vector.
value_type singularPointAtRank (size_type rank) const
Get singular point at given rank.
vector_t derivBeforeSingularPoint (size_type rank, size_type order) const
Get left limit value of derivative at given singular point.
vector_t derivAfterSingularPoint (size_type rank, size_type order) const
Get right limit value of derivative at given singular point.
jacobian_t variationConfigWrtParam (StableTimePoint tp) const throw ()
jacobian_t variationDerivWrtParam (StableTimePoint tp, size_type order) const throw ()
Protected Member Functions
void impl_compute (result_t &result, double t) const throw ()
void impl_derivative (gradient_t &derivative, double argument, size_type order=1) const throw ()
void impl_derivative (gradient_t &g, StableTimePoint, size_type order) const throw ()
Trajectory< 3 > * resize (interval_t timeRange) const throw ()
Clone and resize a trajectory.
Detailed Description
Takes a vector or argument and differentiate it.
It is common to have an optimization vector where a pattern is repeated:
[x_0^0 ... x_N^0 ... x_0^M x_N^M]
The pattern is here of length N and repeated M times.
By using numerical interpolation, it is possible to differentiate this pattern.
A classical example are trajectories.
Member Typedef Documentation
typedef boost::shared_ptr<VectorInterpolation> roboptim::VectorInterpolation::VectorInterpolationShPtr_t
Constructor & Destructor Documentation
roboptim::VectorInterpolation::VectorInterpolation (const vector_t & x, size_type outputSize, value_type dt) throw (std::runtime_error) [inline, explicit]
roboptim::VectorInterpolation::~VectorInterpolation () throw () [inline]
Member Function Documentation
VectorInterpolation::vector_t roboptim::VectorInterpolation::derivAfterSingularPoint (size_type rank, size_type order) const [inline, virtual]
Get right limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Return values:
derivative Limit of the derivative at singular point for decreasing parameter values.
Implements roboptim::Trajectory< 3 >.
VectorInterpolation::vector_t roboptim::VectorInterpolation::derivBeforeSingularPoint (size_type rank, size_type order) const [inline, virtual]
Get left limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Returns:
Limit of the derivative at singular point for increasing parameter values.
Implements roboptim::Trajectory< 3 >.
void roboptim::VectorInterpolation::impl_compute (result_t & result, double t) const throw () [inline, protected]
void roboptim::VectorInterpolation::impl_derivative (gradient_t & derivative, double argument, size_type order = 1) const throw () [inline, protected]
void roboptim::VectorInterpolation::impl_derivative (gradient_t & g, StableTimePoint stp, size_type order) const throw () [inline, protected, virtual]
Implements roboptim::Trajectory< 3 >.
References roboptim::StableTimePoint::getTime().
Trajectory< 3 > * roboptim::VectorInterpolation::resize (interval_t timeRange) const throw () [inline, protected, virtual]
Clone and resize a trajectory.
Implements roboptim::Trajectory< 3 >.
roboptim::VectorInterpolation::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS (Trajectory< 3 >)
roboptim::VectorInterpolation::ROBOPTIM_IMPLEMENT_CLONE (VectorInterpolation)
void roboptim::VectorInterpolation::setParameters (const vector_t & x) throw (std::runtime_error) [inline, virtual]
Store parameters and update coefficients.
Reimplemented from roboptim::Trajectory< 3 >.
References roboptim::Trajectory< DerivabilityOrder >::setParameters().
VectorInterpolation::value_type roboptim::VectorInterpolation::singularPointAtRank (size_type rank) const [inline, virtual]
Get singular point at given rank.
Implements roboptim::Trajectory< 3 >.
VectorInterpolation::jacobian_t roboptim::VectorInterpolation::variationConfigWrtParam (double t) const throw () [inline, virtual]
Get the variation of a configuration with respect to parameter vector.
Parameters:
t value in the definition interval.
Returns:
Jacobian:
Implements roboptim::Trajectory< 3 >.
VectorInterpolation::jacobian_t roboptim::VectorInterpolation::variationConfigWrtParam (StableTimePoint tp) const throw () [inline, virtual]
Implements roboptim::Trajectory< 3 >.
VectorInterpolation::jacobian_t roboptim::VectorInterpolation::variationDerivWrtParam (double t, size_type order) const throw () [inline, virtual]
Get the variation of a derivative with respect to parameter vector.
Parameters:
t value in the definition interval.
order order of the derivative.
Returns:
jacobian
Implements roboptim::Trajectory< 3 >.
VectorInterpolation::jacobian_t roboptim::VectorInterpolation::variationDerivWrtParam (StableTimePoint tp, size_type order) const throw () [inline, virtual]
Implements roboptim::Trajectory< 3 >.
References roboptim::StableTimePoint::getTime().