roboptim::BSpline< N > Class Template Reference
roboptim::BSpline< N > Class Template Reference
Mathematical functions
#include <roboptim/trajectory/b-spline.hh>
Public Types
typedef Trajectory< N > parent_t
Parent type.
typedef parent_t::interval_t interval_t
Import interval type.
typedef parent_t::size_type size_type
Import size type.
typedef parent_t::value_type value_type
Import value type.
typedef parent_t::vector_t vector_t
Import vector type.
typedef parent_t::matrix_t matrix_t
typedef parent_t::result_t result_t
Import result type.
typedef parent_t::gradient_t gradient_t
Import gradient type.
typedef parent_t::jacobian_t jacobian_t
Import jacobian type.
Public Member Functions
BSpline (interval_t timeRange, size_type dimension, const vector_t &parameters, const std::string name="B-Spline") throw ()
Instantiate a B-Spline from its definition.
BSpline (interval_t tr, size_type dimension, const vector_t &parameters, const vector_t &knots, std::string name="B-Spline") throw ()
Instantiate a B-Spline with parameters and knot points.
BSpline (const BSpline< N > &spline) throw ()
Copy constructor.
virtual ~BSpline () throw ()
virtual void setParameters (const vector_t &) throw ()
Modify spline parameters.
virtual jacobian_t variationConfigWrtParam (double t) const throw ()
Get the variation of a configuration with respect to parameter vector.
virtual jacobian_t variationDerivWrtParam (double t, size_type order) const throw ()
Get the variation of a derivative with respect to parameter vector.
virtual value_type singularPointAtRank (size_type rank) const
Get singular point at given rank.
virtual vector_t derivBeforeSingularPoint (size_type rank, size_type order) const
Get left limit value of derivative at given singular point.
virtual vector_t derivAfterSingularPoint (size_type rank, size_type order) const
Get right limit value of derivative at given singular point.
virtual Trajectory< N > * resize (interval_t timeRange) const throw ()
Clone and resize a trajectory.
virtual std::ostream & print (std::ostream &o) const throw ()
Display the function on the specified output stream.
jacobian_t variationConfigWrtParam (StableTimePoint tp) const throw ()
jacobian_t variationDerivWrtParam (StableTimePoint tp, size_type order) const throw ()
value_type Dt () const ROBOPTIM_TRAJECTORY_DEPRECATED
vector_t const & knots () const
size_type interval (value_type t) const
Protected Types
typedef Polynomial< N > polynomial_t
typedef Monomial< N > monomial_t
typedef std::map< int,
polynomial_t > cox_map
typedef cox_map::iterator cox_map_itr_t
Protected Member Functions
void impl_compute (result_t &, double) const throw ()
void impl_derivative (gradient_t &g, double x, size_type order) const throw ()
void impl_derivative (gradient_t &g, StableTimePoint, size_type order) const throw ()
vector_t basisFunctions (value_type t, size_type order) const ROBOPTIM_TRAJECTORY_DEPRECATED
void computeBasisPolynomials ()
cox_map cox_de_boor (size_type j, size_type n) const
Generate base polynomial set For the basic spline formula noted in the pdf from the docs section, this implements (3), the recursion formula.
Static Protected Attributes
static const size_type order_ = N
order of the B-Spline
static log4cxx::LoggerPtr logger
Pointer to B-spline logger (see log4cxx documentation).
template<int N>
class roboptim::BSpline< N >
Member Typedef Documentation
template<int N> typedef std::map<int, polynomial_t> roboptim::BSpline< N >::cox_map [protected]
template<int N> typedef cox_map::iterator roboptim::BSpline< N >::cox_map_itr_t [protected]
template<int N> typedef parent_t::gradient_t roboptim::BSpline< N >::gradient_t
Import gradient type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::interval_t roboptim::BSpline< N >::interval_t
Import interval type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::jacobian_t roboptim::BSpline< N >::jacobian_t
Import jacobian type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::matrix_t roboptim::BSpline< N >::matrix_t
template<int N> typedef Monomial<N> roboptim::BSpline< N >::monomial_t [protected]
template<int N> typedef Trajectory<N> roboptim::BSpline< N >::parent_t
Parent type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef Polynomial<N> roboptim::BSpline< N >::polynomial_t [protected]
template<int N> typedef parent_t::result_t roboptim::BSpline< N >::result_t
Import result type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::size_type roboptim::BSpline< N >::size_type
Import size type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::value_type roboptim::BSpline< N >::value_type
Import value type.
Reimplemented from roboptim::Trajectory< N >.
template<int N> typedef parent_t::vector_t roboptim::BSpline< N >::vector_t
Import vector type.
Reimplemented from roboptim::Trajectory< N >.
Constructor & Destructor Documentation
template<int N> roboptim::BSpline< N >::BSpline (interval_t timeRange, size_type dimension, const vector_t & parameters, const std::string name = "B-Spline") throw ()
Instantiate a B-Spline from its definition.
Parameters:
timeRange spline time range: $
dimension spline dimension:
parameters vector of parameters defining control points
name function title
Number of control points is inferred from dimension of dimenion of parameter vector.
template<int N> roboptim::BSpline< N >::BSpline (interval_t tr, size_type dimension, const vector_t & parameters, const vector_t & knots, std::string name = "B-Spline") throw ()
Instantiate a B-Spline with parameters and knot points.
Parameters:
timeRange spline time range: $
dimension spline dimension:
parameters vector of parameters
knots vector of control points
name function title The number of knot points must be the number of parameters + N + 1. In the knot vector, N knots at the beginning must lie before the start of the spline. The rest of the knot point must lie before the end of the spline interval.
template<int N> roboptim::BSpline< N >::BSpline (const BSpline< N > & spline) throw ()
Copy constructor.
Parameters:
spline spline that will be copied
template<int N> virtual roboptim::BSpline< N >::~BSpline () throw () [inline, virtual]
Member Function Documentation
template<int N> BSpline< N >::vector_t roboptim::BSpline< N >::basisFunctions (value_type t, size_type order) const [protected]
References roboptim::Polynomial< N >::derivative(), and roboptim::detail::fixTime().
template<int N> void roboptim::BSpline< N >::computeBasisPolynomials () [protected]
template<int N> BSpline< N >::cox_map roboptim::BSpline< N >::cox_de_boor (size_type j, size_type n) const [protected]
Generate base polynomial set For the basic spline formula noted in the pdf from the docs section, this implements (3), the recursion formula.
It returns the results as factors of b_j,0 where j is the index of the returned map.
Parameters:
j current knot index
n current basis function order
Returns:
a std::map. Call this with j as the index of the knot for which spline segment your want to generate the basis function for, and n as the order of your spline.
References roboptim::Polynomial< N >::coefs().
template<int N> BSpline< N >::vector_t roboptim::BSpline< N >::derivAfterSingularPoint (size_type rank, size_type order) const [virtual]
Get right limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Return values:
derivative Limit of the derivative at singular point for decreasing parameter values.
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::vector_t roboptim::BSpline< N >::derivBeforeSingularPoint (size_type rank, size_type order) const [virtual]
Get left limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Returns:
Limit of the derivative at singular point for increasing parameter values.
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::value_type roboptim::BSpline< N >::Dt () const
template<int N> void roboptim::BSpline< N >::impl_compute (result_t & derivative, double t) const throw () [protected]
References roboptim::detail::fixTime().
template<int N> void roboptim::BSpline< N >::impl_derivative (gradient_t & g, double x, size_type order) const throw () [protected]
NDEBUG
NDEBUG
References roboptim::Polynomial< N >::derivative(), and roboptim::detail::fixTime().
template<int N> void roboptim::BSpline< N >::impl_derivative (gradient_t & g, StableTimePoint stp, size_type order) const throw () [protected, virtual]
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::size_type roboptim::BSpline< N >::interval (value_type t) const
References roboptim::detail::fixTime().
template<int N> BSpline< N >::vector_t const & roboptim::BSpline< N >::knots () const
template<int N> std::ostream & roboptim::BSpline< N >::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::Trajectory< N >.
template<int N> Trajectory< N > * roboptim::BSpline< N >::resize (interval_t timeRange) const throw () [virtual]
Clone and resize a trajectory.
Implements roboptim::Trajectory< N >.
template<int N> void roboptim::BSpline< N >::setParameters (const vector_t & p) throw () [virtual]
Modify spline parameters.
Reimplemented from roboptim::Trajectory< N >.
template<int N> BSpline< N >::value_type roboptim::BSpline< N >::singularPointAtRank (size_type rank) const [virtual]
Get singular point at given rank.
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::jacobian_t roboptim::BSpline< N >::variationConfigWrtParam (double t) const throw () [virtual]
Get the variation of a configuration with respect to parameter vector.
Parameters:
t value in the definition interval.
Returns:
Jacobian:
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::jacobian_t roboptim::BSpline< N >::variationConfigWrtParam (StableTimePoint tp) const throw () [virtual]
Implements roboptim::Trajectory< N >.
template<int N> BSpline< N >::jacobian_t roboptim::BSpline< N >::variationDerivWrtParam (double t, size_type order) const throw () [virtual]
Get the variation of a derivative with respect to parameter vector.
Parameters:
t value in the definition interval.
order order of the derivative.
Returns:
jacobian
Implements roboptim::Trajectory< N >.
References roboptim::Polynomial< N >::derivative(), and roboptim::detail::fixTime().
template<int N> BSpline< N >::jacobian_t roboptim::BSpline< N >::variationDerivWrtParam (StableTimePoint tp, size_type order) const throw () [virtual]
Implements roboptim::Trajectory< N >.
Member Data Documentation
template<int N> const size_type roboptim::BSpline< N >::order_ = N [static, protected]
order of the B-Spline