roboptim::visualization::gnuplot Namespace Reference
roboptim::visualization::gnuplot Namespace Reference
Gnuplot rendering.
Namespaces
namespace detail
Functions
template<unsigned dorder>
Command plot_limitSpeed (const Trajectory< dorder > &trajectory, boost::optional< double > vMax=boost::optional< double >(), typename Trajectory< dorder >::value_type step=.01)
Plot a speed limit constraint.
template<typename T >
Command plot_speeds (const T &traj, typename T::value_type step=.01)
template<unsigned N>
Command plot_xy (const Trajectory< N > &traj, typename Trajectory< N >::value_type step=.01)
Plot a 2D trajectory with Gnuplot.
template<typename T >
Command plot_xytheta (const T &traj, typename T::value_type step=.01)
Detailed Description
Gnuplot rendering.
Gnuplot display classes.
Function Documentation
template<unsigned dorder> Command roboptim::visualization::gnuplot::plot_limitSpeed (const Trajectory< dorder > & trajectory, boost::optional< double > vMax = boost::optional<double> (), typename Trajectory< dorder >::value_type step = .01)
Plot a speed limit constraint.
Returns:
Gnuplot command
Examples:
spline-time-optimization.cc.
References roboptim::Trajectory< DerivabilityOrder >::timeRange().
template<typename T > Command roboptim::visualization::gnuplot::plot_speeds (const T & traj, typename T::value_type step = .01)
References roboptim::StableTimePoint::getTime(), and roboptim::tMax.
template<unsigned N> Command roboptim::visualization::gnuplot::plot_xy (const Trajectory< N > & traj, typename Trajectory< N >::value_type step = .01)
Plot a 2D trajectory with Gnuplot.
Plot a 2D trajectory in Gnuplot.
Parameters:
traj trajectory to be displayed
step discretization step.
Returns:
Gnuplot command
Examples:
spline-optimization.cc.
References roboptim::Trajectory< DerivabilityOrder >::timeRange(), and roboptim::tMax.
template<typename T > Command roboptim::visualization::gnuplot::plot_xytheta (const T & traj, typename T::value_type step = .01)
References roboptim::StableTimePoint::getTime(), and roboptim::tMax.