roboptim::Polynomial< N > Class Template Reference
roboptim::Polynomial< N > Class Template Reference
Polynomial of degree at most N.
#include <roboptim/trajectory/polynomial.hh>
Public Types
typedef Function::size_type size_type
typedef Function::value_type value_type
typedef Function::vector_t vector_t
typedef Eigen::Matrix
< value_type, N+1, 1 > coefs_t
Public Member Functions
Polynomial ()
Default constructor: return a null polynomial.
Polynomial (value_type t0, const vector_t &coefs)
Construct of a polynomial from its center and its coefficients.
Polynomial (value_type t0,...)
Variadic constructor.
template<int M>
Polynomial (const Polynomial< M > &p)
Copy constructor of polynomials of different orders.
Polynomial< N > translate (value_type t1) const
Return a new polynomial translated from (t-t₀) to (t-t₁).
void translateInPlace (value_type t1)
Translate the polynomial (in place) from (t-t₀) to (t-t₁).
value_type derivative (value_type t, size_type order=1) const
Evaluate the derivative of a given order.
template<int M>
Polynomial< N+M > operator* (const Polynomial< M > &poly) const
Multiply polynomials of different orders.
Polynomial< N > operator+ (const Polynomial< N > &poly) const
Addition of polynomials.
Polynomial< N > operator- (const Polynomial< N > &poly) const
Subtraction of polynomials.
Polynomial< N > operator* (value_type lambda) const
Scalar multiplication of a polynomial.
value_type operator() (value_type t) const
Evaluate the polynomial.
const coefs_t & coefs () const
Const getter to coefs.
coefs_t & coefs ()
Getter to coefs.
value_type t0 () const
Const getter to t0.
value_type & t0 ()
Reference to t0.
value_type operator[] (int i) const
Get the i-th polynomial coefficient.
std::vector< value_type > realRoots () const throw (std::runtime_error)
Return the real roots of the polynomial.
bool isConstant () const
Return whether the polynomial is constant.
Static Public Member Functions
static int order ()
Return the order of such a polynomial.
Protected Types
enum special_polynomials {
all_zero_coefficients = 0,
monomial_coefficients = 1
}
Enum for special polynomials.
Protected Member Functions
value_type impl_derivative (value_type t, size_type order, size_type start_coef=0) const
coefs_t impl_translate (value_type t1) const
Polynomial (value_type t0, special_polynomials key)
Special constructor for Monomial<N> and some operators.
Static Protected Attributes
static const int order_ = N
order of the polynomial.
Detailed Description
template<int N>
class roboptim::Polynomial< N >
Polynomial of degree at most N.
Member Typedef Documentation
template<int N> typedef Eigen::Matrix<value_type, N+1, 1> roboptim::Polynomial< N >::coefs_t
template<int N> typedef Function::size_type roboptim::Polynomial< N >::size_type
template<int N> typedef Function::value_type roboptim::Polynomial< N >::value_type
Reimplemented in roboptim::Monomial< N >.
template<int N> typedef Function::vector_t roboptim::Polynomial< N >::vector_t
Member Enumeration Documentation
template<int N> enum roboptim::Polynomial::special_polynomials [protected]
Enum for special polynomials.
Enumerator:
all_zero_coefficients
Null polynomial: 0.
monomial_coefficients
Monomial polynomial: (t-t₀)
Constructor & Destructor Documentation
template<int N> roboptim::Polynomial< N >::Polynomial ()
Default constructor: return a null polynomial.
template<int N> roboptim::Polynomial< N >::Polynomial (value_type t0, const vector_t & coefs)
Construct of a polynomial from its center and its coefficients.
Parameters:
t0 polynomial of (t-t₀).
coefs polynomial coefficients.
References roboptim::Polynomial< N >::coefs().
template<int N> roboptim::Polynomial< N >::Polynomial (value_type t0, ...)
Variadic constructor.
Note: this is a legacy constructor used to keep Polynomial3's API.
Parameters:
t0 polynomial of (t-t₀).
... variadic arguments containing [a₀,a₁,...,a_N]
template<int N> template<int M> roboptim::Polynomial< N >::Polynomial (const Polynomial< M > & p)
Copy constructor of polynomials of different orders.
Warning:
If N < M, coefficients of higher degrees will be discarded. This is only valid if you are considering |t-t₀|«1.
Template Parameters:
M degree of the copied polynomial.
Parameters:
p copied polynomial.
References roboptim::Polynomial< N >::coefs().
template<int N> roboptim::Polynomial< N >::Polynomial (value_type t0, special_polynomials key) [protected]
Special constructor for Monomial<N> and some operators.
Parameters:
t0
key one of all_zero_coefficients, monomial_coefficients.
References roboptim::Polynomial< N >::all_zero_coefficients, and roboptim::Polynomial< N >::monomial_coefficients.
Member Function Documentation
template<int N> const Polynomial< N >::coefs_t & roboptim::Polynomial< N >::coefs () const
Const getter to coefs.
Returns:
const reference to polynomial coefficients.
Referenced by roboptim::BSpline< N >::cox_de_boor(), roboptim::Polynomial< N >::operator*(), and roboptim::Polynomial< N >::Polynomial().
template<int N> Polynomial< N >::coefs_t & roboptim::Polynomial< N >::coefs ()
Getter to coefs.
Returns:
reference to polynomial coefficients.
template<int N> Polynomial< N >::value_type roboptim::Polynomial< N >::derivative (value_type t, size_type order = 1) const
Evaluate the derivative of a given order.
Parameters:
t time of the evaluation.
order order of the derivative.
Returns:
derivative of a given order evaluated at t.
Referenced by roboptim::BSpline< N >::basisFunctions(), roboptim::CubicBSpline::impl_derivative(), roboptim::BSpline< N >::impl_derivative(), roboptim::CubicBSpline::variationDerivWrtParam(), roboptim::BSpline< N >::variationDerivWrtParam(), and roboptim::ConstrainedBSpline< N >::variationDerivWrtParam().
template<int N> Polynomial< N >::value_type roboptim::Polynomial< N >::impl_derivative (value_type t, size_type order, size_type start_coef = 0) const [protected]
template<int N> Polynomial< N >::coefs_t roboptim::Polynomial< N >::impl_translate (value_type t1) const [protected]
template<int N> bool roboptim::Polynomial< N >::isConstant () const
Return whether the polynomial is constant.
Returns:
true if the polynomial is constant, false otherwise.
template<int N> Polynomial< N >::value_type roboptim::Polynomial< N >::operator() (value_type t) const
Evaluate the polynomial.
Parameters:
t point of evaluation.
Returns:
P(t)
template<int N> template<int M> Polynomial< N+M > roboptim::Polynomial< N >::operator* (const Polynomial< M > & poly) const
Multiply polynomials of different orders.
Template Parameters:
M order of the polynomial.
Parameters:
poly polynomial to multiply.
Returns:
P₀P₁
References roboptim::Polynomial< N >::coefs(), and roboptim::Polynomial< N >::translate().
template<int N> Polynomial< N > roboptim::Polynomial< N >::operator* (value_type lambda) const
Scalar multiplication of a polynomial.
Parameters:
lambda scalar.
Returns:
λP
template<int N> Polynomial< N > roboptim::Polynomial< N >::operator+ (const Polynomial< N > & poly) const
Addition of polynomials.
Parameters:
poly polynomial to add.
Returns:
P₀ + P₁
References roboptim::Polynomial< N >::translate().
template<int N> Polynomial< N > roboptim::Polynomial< N >::operator- (const Polynomial< N > & poly) const
Subtraction of polynomials.
Parameters:
poly polynomial to subtract.
Returns:
P₀ - P₁
References roboptim::Polynomial< N >::translate().
template<int N> Polynomial< N >::value_type roboptim::Polynomial< N >::operator[] (int i) const
Get the i-th polynomial coefficient.
Parameters:
i number of the coefficient to get.
Returns:
i-th polynomial coefficient αi, with: α_i (t-t₀)^i
template<int N> static int roboptim::Polynomial< N >::order () [inline, static]
Return the order of such a polynomial.
Returns:
order of such a polynomial.
References roboptim::Polynomial< N >::order_.
template<int N> std::vector< typename Polynomial< N >::value_type > roboptim::Polynomial< N >::realRoots () const throw (std::runtime_error)
Return the real roots of the polynomial.
Warning:
This function relies on Eigen's experimental polynomial solver.
Returns:
vector of the real roots of the polynomial.
Exceptions:
std::runtime_error invalid polynomial (e.g. null).
template<int N> Polynomial< N >::value_type roboptim::Polynomial< N >::t0 () const
Const getter to t0.
Returns:
t0.
template<int N> Polynomial< N >::value_type & roboptim::Polynomial< N >::t0 ()
Reference to t0.
Returns:
reference to t0.
template<int N> Polynomial< N > roboptim::Polynomial< N >::translate (value_type t1) const
Return a new polynomial translated from (t-t₀) to (t-t₁).
Parameters:
t1 new center.
Returns:
polynomial translated to (t-t₁)
Referenced by roboptim::Polynomial< N >::operator*(), roboptim::Polynomial< N >::operator+(), and roboptim::Polynomial< N >::operator-().
template<int N> void roboptim::Polynomial< N >::translateInPlace (value_type t1)
Translate the polynomial (in place) from (t-t₀) to (t-t₁).
Parameters:
t1 new center.
Member Data Documentation
template<int N> const int roboptim::Polynomial< N >::order_ = N [static, protected]
order of the polynomial.
Referenced by roboptim::Polynomial< N >::order().