roboptim::CubicBSpline Class Reference
roboptim::CubicBSpline Class Reference
Mathematical functions
Cubic B-Spline trajectory.
#include <roboptim/trajectory/cubic-b-spline.hh>
Public Member Functions
CubicBSpline (interval_t timeRange, size_type dimension, const vector_t &parameters, const std::string name="cubic B-Spline") throw ()
Instantiate a cubic B-Spline from its definition.
CubicBSpline (const CubicBSpline &spline) throw ()
Copy constructor.
virtual ~CubicBSpline () throw ()
virtual void setParameters (const vector_t &) throw ()
Modify spline parameters.
virtual jacobian_t variationConfigWrtParam (double t) const throw ()
Get the variation of a configuration with respect to parameter vector.
virtual jacobian_t variationDerivWrtParam (double t, size_type order) const throw ()
Get the variation of a derivative with respect to parameter vector.
virtual value_type singularPointAtRank (size_type rank) const
Get singular point at given rank.
virtual vector_t derivBeforeSingularPoint (size_type rank, size_type order) const
Get left limit value of derivative at given singular point.
virtual vector_t derivAfterSingularPoint (size_type rank, size_type order) const
Get right limit value of derivative at given singular point.
virtual Trajectory
< derivabilityOrder > * resize (interval_t timeRange) const throw ()
Clone and resize a trajectory.
virtual std::ostream & print (std::ostream &o) const throw ()
Display the function on the specified output stream.
jacobian_t variationConfigWrtParam (StableTimePoint tp) const throw ()
jacobian_t variationDerivWrtParam (StableTimePoint tp, size_type order) const throw ()
template<typename P >
void freezeCurveStart (P &problem, size_type offset=0) const throw ()
Add a constraint to a problem in order to freeze the B-spline at its start.
template<typename P >
void freezeCurveEnd (P &problem, size_type offset=0) const throw ()
Add a constraint to a problem in order to freeze the B-spline at its end.
value_type Dt () const ROBOPTIM_TRAJECTORY_DEPRECATED
Regular spacing between B-spline knots.
void translateBasisPolynomials (double t1) throw ()
Translate the basis polynomials to a given time t1.
void toPolynomials (std::vector< Polynomial3 > &res) const throw ()
Return the polynomial expression of the cubic B-spline on each time interval.
const std::vector< std::vector
< Polynomial3 > > & basisPolynomials () const
Constant getter for the basis polynomials of the cubic B-spline.
size_type getNumberControlPoints () const
Get the number of control points of the spline.
const std::vector< value_type > & knot_vector () const
Return the knot vector of the spline.
Protected Member Functions
void impl_compute (result_t &, double) const throw ()
void impl_derivative (gradient_t &g, double x, size_type order) const throw ()
void impl_derivative (gradient_t &g, StableTimePoint, size_type order) const throw ()
size_type interval (value_type t) const
Find the index of the interval in which t is.
void computeBasisPolynomials ()
Compute the basis polynomials for the cubic B-spline.
vector_t basisFunctions (value_type t, size_type order) const ROBOPTIM_TRAJECTORY_DEPRECATED
Compute the basis functions for a given instant t.
Detailed Description
Cubic B-Spline trajectory.
Implement a B-Spline as a trajectory as described in doc/cubic-b-spline.tex
Examples:
spline-optimization.cc, and spline-time-optimization.cc.
Constructor & Destructor Documentation
roboptim::CubicBSpline::CubicBSpline (interval_t timeRange, size_type dimension, const vector_t & parameters, const std::string name = "cubic B-Spline") throw ()
Instantiate a cubic B-Spline from its definition.
Parameters:
timeRange spline time range: $
dimension spline dimension:
parameters vector of parameters defining control points
name function title
Number of control points is inferred from dimension of dimenion of parameter vector.
Referenced by resize().
roboptim::CubicBSpline::CubicBSpline (const CubicBSpline & spline) throw ()
Copy constructor.
Parameters:
spline spline that will be copied
roboptim::CubicBSpline::~CubicBSpline () throw () [virtual]
Member Function Documentation
CubicBSpline::vector_t roboptim::CubicBSpline::basisFunctions (value_type t, size_type order) const [protected]
Compute the basis functions for a given instant t.
Parameters:
t instant considered.
order order of the basis functions.
Returns:
basis functions evaluated at t.
References Dt(), roboptim::detail::fixTime(), interval(), roboptim::Trajectory< 3 >::length(), roboptim::Trajectory< 3 >::timeRange(), and roboptim::Trajectory< 3 >::tolerance().
const std::vector<std::vector <Polynomial3> >& roboptim::CubicBSpline::basisPolynomials () const [inline]
Constant getter for the basis polynomials of the cubic B-spline.
Returns:
constant reference to the basis polynomials.
Note: computeBasisPolynomials() needs to be called beforehand (which is done in the CubicBSpline constructor).
void roboptim::CubicBSpline::computeBasisPolynomials () [protected]
Compute the basis polynomials for the cubic B-spline.
CubicBSpline::vector_t roboptim::CubicBSpline::derivAfterSingularPoint (size_type rank, size_type order) const [virtual]
Get right limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Return values:
derivative Limit of the derivative at singular point for decreasing parameter values.
Implements roboptim::Trajectory< 3 >.
References roboptim::Trajectory< 3 >::derivative(), and singularPointAtRank().
CubicBSpline::vector_t roboptim::CubicBSpline::derivBeforeSingularPoint (size_type rank, size_type order) const [virtual]
Get left limit value of derivative at given singular point.
Parameters:
rank rank of the singular points.
order order of derivation.
Returns:
Limit of the derivative at singular point for increasing parameter values.
Implements roboptim::Trajectory< 3 >.
References roboptim::Trajectory< 3 >::derivative(), and singularPointAtRank().
CubicBSpline::value_type roboptim::CubicBSpline::Dt () const
Regular spacing between B-spline knots.
This is only valid for uniform B-splines.
Returns:
regular spacing between B-spline knots.
References roboptim::Trajectory< 3 >::length().
Referenced by basisFunctions().
template<typename P > void roboptim::CubicBSpline::freezeCurveEnd (P & problem, size_type offset = 0) const throw ()
Add a constraint to a problem in order to freeze the B-spline at its end.
Parameters:
problem problem to which the constraint will be added.
offset offset of the B-spline parameters in the problem's parameter list.
Examples:
spline-optimization.cc, and spline-time-optimization.cc.
template<typename P > void roboptim::CubicBSpline::freezeCurveStart (P & problem, size_type offset = 0) const throw ()
Add a constraint to a problem in order to freeze the B-spline at its start.
Parameters:
problem problem to which the constraint will be added.
offset offset of the B-spline parameters in the problem's parameter list.
Examples:
spline-optimization.cc, and spline-time-optimization.cc.
size_type roboptim::CubicBSpline::getNumberControlPoints () const [inline]
Get the number of control points of the spline.
Returns:
Number of control points of the spline.
void roboptim::CubicBSpline::impl_compute (result_t & derivative, double t) const throw () [protected]
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::detail::fixTime().
void roboptim::CubicBSpline::impl_derivative (gradient_t & g, double x, size_type order) const throw () [protected]
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::Polynomial< N >::derivative(), and roboptim::detail::fixTime().
void roboptim::CubicBSpline::impl_derivative (gradient_t & g, StableTimePoint stp, size_type order) const throw () [protected, virtual]
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Implements roboptim::Trajectory< 3 >.
CubicBSpline::size_type roboptim::CubicBSpline::interval (value_type t) const [protected]
Find the index of the interval in which t is.
Parameters:
t instant considered.
Returns:
index of the interval in which t is.
References roboptim::detail::fixTime(), and roboptim::Trajectory< 3 >::timeRange().
Referenced by basisFunctions().
const std::vector<value_type>& roboptim::CubicBSpline::knot_vector () const [inline]
Return the knot vector of the spline.
Returns:
knot vector of the spline (const).
std::ostream & roboptim::CubicBSpline::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::Trajectory< 3 >.
virtual Trajectory<derivabilityOrder>* roboptim::CubicBSpline::resize (interval_t timeRange) const throw () [inline, virtual]
Clone and resize a trajectory.
Implements roboptim::Trajectory< 3 >.
References CubicBSpline().
void roboptim::CubicBSpline::setParameters (const vector_t & p) throw () [virtual]
Modify spline parameters.
Reimplemented from roboptim::Trajectory< 3 >.
Referenced by roboptim::SplineLength::impl_compute(), and roboptim::SplineLength::impl_gradient().
CubicBSpline::value_type roboptim::CubicBSpline::singularPointAtRank (size_type rank) const [virtual]
Get singular point at given rank.
Implements roboptim::Trajectory< 3 >.
References roboptim::Trajectory< 3 >::length().
Referenced by derivAfterSingularPoint(), and derivBeforeSingularPoint().
void roboptim::CubicBSpline::toPolynomials (std::vector< Polynomial3 > & res) const throw ()
Return the polynomial expression of the cubic B-spline on each time interval.
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
void roboptim::CubicBSpline::translateBasisPolynomials (double t1) throw ()
Translate the basis polynomials to a given time t1.
Parameters:
t1 new center time, i.e. P = sum(a_i*(t-t1)^i, i={0,3})
This method can be useful when one needs to have all the polynomials expressed in the same basis (e.g. t1 = 0).
CubicBSpline::jacobian_t roboptim::CubicBSpline::variationConfigWrtParam (double t) const throw () [virtual]
Get the variation of a configuration with respect to parameter vector.
Parameters:
t value in the definition interval.
Returns:
Jacobian:
Implements roboptim::Trajectory< 3 >.
Examples:
spline-optimization.cc.
CubicBSpline::jacobian_t roboptim::CubicBSpline::variationConfigWrtParam (StableTimePoint tp) const throw () [virtual]
Implements roboptim::Trajectory< 3 >.
CubicBSpline::jacobian_t roboptim::CubicBSpline::variationDerivWrtParam (double t, size_type order) const throw () [virtual]
Get the variation of a derivative with respect to parameter vector.
Parameters:
t value in the definition interval.
order order of the derivative.
Returns:
jacobian
Implements roboptim::Trajectory< 3 >.
References roboptim::Polynomial< N >::derivative(), and roboptim::detail::fixTime().
CubicBSpline::jacobian_t roboptim::CubicBSpline::variationDerivWrtParam (StableTimePoint tp, size_type order) const throw () [virtual]
Implements roboptim::Trajectory< 3 >.