roboptim Namespace Reference
roboptim Namespace Reference
Meta-functions, functions and solvers related classes.
Namespaces
namespace detail
namespace visualization
Graphic visualization.
Classes
class AnthropomorphicCostFunction
Cost function from ``An optimal control model unifying holonomic and nonholonomic walking'' Katja Mombaur, Jean-Paul Laumond, Eiichi Yoshida (2008 8th IEEE-RAS Interational Conference on Humanoid Robots).
class BSpline
class CubicBSpline
Cubic B-Spline trajectory.
class FreeTimeTrajectory
Decorate a trajectory to make time scalable.
class Freeze
Add constraints that freeze parameters.
class FrontalSpeed
class LimitOmega
class LimitSpeed
class OrthogonalSpeed
class Polynomial
Polynomial of degree at most N.
struct Monomial
Monomial
.
class SplineLength
Approximate the length of a Spline.
class StablePointStateFunction
Trajectory cost function defined by state evaluation at parameter.
class TMax
class StableTimePoint
class StateFunction
Trajectory cost function defined by state evaluation at parameter.
class TrajectoryCost
Meta-function for trajectory cost.
class TrajectorySumCost
Trajectory cost function defined by sum of state evaluations at parameters.
class Trajectory
Abstract trajectory.
class VectorInterpolation
Takes a vector or argument and differentiate it.
Typedefs
typedef Polynomial< 3 > Polynomial3
Polynomial of degree at most 3.
typedef Monomial< 3 > Monomial3
Monomial3
.
Functions
Function::vector_t addScaleToParameters (const Function::vector_t &p, Function::value_type t=1.)
Function::vector_t removeScaleFromParameters (const Function::vector_t &v)
template<typename P >
Freeze< P > makeFreeze (P &problem) throw ()
template<int N>
Polynomial< N > operator* (typename Polynomial< N >::value_type lambda, const Polynomial< N > &poly)
template<int N>
std::ostream & operator<< (std::ostream &stream, const Polynomial< N > &p)
StableTimePoint operator* (Function::value_type alpha, TMax)
StableTimePoint operator* (TMax, Function::value_type alpha)
boost::shared_ptr
< VectorInterpolation > vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt=1.)
Variables
static const TMax tMax = TMax ()
Detailed Description
Meta-functions, functions and solvers related classes.
Typedef Documentation
typedef Monomial<3> roboptim::Monomial3
Monomial3
.
typedef Polynomial<3> roboptim::Polynomial3
Polynomial of degree at most 3.
Function Documentation
Function::vector_t roboptim::addScaleToParameters (const Function::vector_t & p, Function::value_type t = 1.) [inline]
template<typename P > Freeze<P> roboptim::makeFreeze (P & problem) throw ()
StableTimePoint roboptim::operator* (Function::value_type alpha, TMax) [inline]
StableTimePoint roboptim::operator* (TMax , Function::value_type alpha) [inline]
template<int N> Polynomial< N > roboptim::operator* (typename Polynomial< N >::value_type lambda, const Polynomial< N > & poly)
template<int N> std::ostream& roboptim::operator<< (std::ostream & stream, const Polynomial< N > & p)
Function::vector_t roboptim::removeScaleFromParameters (const Function::vector_t & v) [inline]
Referenced by roboptim::FreeTimeTrajectory< T >::setParameters().
boost::shared_ptr<VectorInterpolation> roboptim::vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt = 1.) [inline]
Variable Documentation
const TMax roboptim::tMax = TMax () [static]
Referenced by roboptim::LimitOmega< T >::addToProblem(), roboptim::LimitSpeed< T >::addToProblem(), roboptim::StablePointStateFunction< T >::addToProblem(), roboptim::StateFunction< T >::addToProblem(), roboptim::visualization::gnuplot::detail::PlotLimitSpeed< T >::operator()(), roboptim::visualization::gnuplot::plot_speeds(), roboptim::visualization::gnuplot::plot_xy(), roboptim::visualization::gnuplot::plot_xytheta(), roboptim::FreeTimeTrajectory< T >::resize(), and roboptim::FreeTimeTrajectory< T >::unscaleTime().