roboptim::detail Namespace Reference
roboptim::detail Namespace Reference
Classes
struct ComputeIntegral
Functions
Function::value_type unscaleTime (Function::value_type unscaled, Function::value_type min, Function::value_type scale)
template<unsigned dorder>
Function::interval_t unscaleInterval (const Trajectory< dorder > &traj, typename Function::value_type scale)
std::string getLimitSpeedName (const StableTimePoint &timePoint)
template<typename T >
double fixTime (double t, const T &trajectory)
Function Documentation
template<typename T > double roboptim::detail::fixTime (double t, const T & trajectory)
Referenced by roboptim::CubicBSpline::basisFunctions(), roboptim::CubicBSpline::impl_compute(), roboptim::CubicBSpline::impl_derivative(), roboptim::CubicBSpline::interval(), roboptim::FreeTimeTrajectory< T >::scaleTime(), roboptim::FreeTimeTrajectory< T >::unscaleTime(), and roboptim::CubicBSpline::variationDerivWrtParam().
std::string roboptim::detail::getLimitSpeedName (const StableTimePoint & timePoint)
References roboptim::StableTimePoint::getAlpha().
template<unsigned dorder> Function::interval_t roboptim::detail::unscaleInterval (const Trajectory< dorder > & traj, typename Function::value_type scale)
References roboptim::Trajectory< DerivabilityOrder >::timeRange(), and unscaleTime().
Referenced by roboptim::FreeTimeTrajectory< T >::setParameters().
Function::value_type roboptim::detail::unscaleTime (Function::value_type unscaled, Function::value_type min, Function::value_type scale) [inline]
Referenced by unscaleInterval().