roboptim::Polynomial3 Class Reference
roboptim::Polynomial3 Class Reference
Polynomial of degree at most 3.
#include <roboptim/trajectory/polynomial-3.hh>
Public Types
typedef Function::size_type size_type
Public Member Functions
Polynomial3 ()
Default constructor: create a null polynomial.
Polynomial3 (double t0, double a0, double a1, double a2, double a3)
Polynomial3 operator* (const Polynomial3 &poly) const
Polynomial3 operator+ (const Polynomial3 &poly) const
Polynomial3 operator- (const Polynomial3 &poly) const
Polynomial3 translate (const double &t1) const
Return a new polynomial translated from (t-t0) to (t-t1).
void translateInPlace (const double &t1)
Translate the polynomial (in place) from (t-t0) to (t-t1).
double operator() (const double &t) const
Evaluate the polynomial.
double derivative (const double &t, size_type order=1) const
Evaluate the derivative of a given order.
std::ostream & print (std::ostream &o) const throw ()
Print Polynomial3.
double operator[] (int i) const
Get the i-th polynomial coefficient.
std::vector< double > realRoots () const
Return the real roots of the translated polynomial.
Public Attributes
double coefs_ [4]
Polynomial coefficients (ordered from lowest to highest degree).
double t0_
Point on which the polynomial is centered.
Detailed Description
Polynomial of degree at most 3.
Member Typedef Documentation
typedef Function::size_type roboptim::Polynomial3::size_type
Constructor & Destructor Documentation
roboptim::Polynomial3::Polynomial3 ()
Default constructor: create a null polynomial.
References coefs_, and t0_.
Referenced by operator*(), operator+(), operator-(), and translate().
roboptim::Polynomial3::Polynomial3 (double t0, double a0, double a1, double a2, double a3)
References coefs_, and t0_.
Member Function Documentation
double roboptim::Polynomial3::derivative (const double & t, size_type order = 1) const
Evaluate the derivative of a given order.
References coefs_, and t0_.
Referenced by roboptim::CubicBSpline::impl_derivative(), and roboptim::CubicBSpline::variationDerivWrtParam().
double roboptim::Polynomial3::operator() (const double & t) const
Evaluate the polynomial.
References coefs_, and t0_.
Polynomial3 roboptim::Polynomial3::operator* (const Polynomial3 & poly) const
References coefs_, Polynomial3(), t0_, and translate().
Polynomial3 roboptim::Polynomial3::operator+ (const Polynomial3 & poly) const
References coefs_, Polynomial3(), t0_, and translate().
Polynomial3 roboptim::Polynomial3::operator- (const Polynomial3 & poly) const
References coefs_, Polynomial3(), t0_, and translate().
double roboptim::Polynomial3::operator[] (int i) const
Get the i-th polynomial coefficient.
Parameters:
i number of the coefficient to get.
Returns:
i-th polynomial coefficient αi, with: α_i (t-t₀)^i
References coefs_.
std::ostream & roboptim::Polynomial3::print (std::ostream & o) const throw ()
Print Polynomial3.
Referenced by roboptim::operator<<().
std::vector< double > roboptim::Polynomial3::realRoots () const
Return the real roots of the translated polynomial.
Warning:
This function relies on Eigen's experimental polynomial solver.
Returns:
vector of the real roots of the translated polynomial.
References coefs_, and translate().
Polynomial3 roboptim::Polynomial3::translate (const double & t1) const
Return a new polynomial translated from (t-t0) to (t-t1).
References coefs_, Polynomial3(), and t0_.
Referenced by operator*(), operator+(), operator-(), and realRoots().
void roboptim::Polynomial3::translateInPlace (const double & t1)
Translate the polynomial (in place) from (t-t0) to (t-t1).
References coefs_, and t0_.
Member Data Documentation
double roboptim::Polynomial3::coefs_[4]
Polynomial coefficients (ordered from lowest to highest degree).
Referenced by derivative(), operator()(), operator*(), roboptim::operator*(), operator+(), operator-(), operator[](), Polynomial3(), realRoots(), translate(), and translateInPlace().
double roboptim::Polynomial3::t0_
Point on which the polynomial is centered.
Referenced by derivative(), operator()(), operator*(), roboptim::operator*(), operator+(), operator-(), Polynomial3(), translate(), and translateInPlace().